import { Image, StyleSheet } from 'react-native';
const styles = StyleSheet.create({
  container1: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: {
    fontSize: 38,
    fontWeight: 'bold',
    letterSpacing: 1,
    marginLeft: 50,
    fontFamily: 'sans-serif',
    color: '#fff',
  },
  input: {
    width: '100%',
    maxWidth: 300,
    height: 45,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderRadius: 10,
    marginBottom: 10,
    backgroundColor: 'rgba(0,0,0,0.05)',
    borderColor: 'rgba(0,0,0,0.3)',
  },
  subtitle: {
    fontSize: 28,
    fontWeight: 'bold',
    letterSpacing: 1,
    margin: 50,
    fontFamily: 'Sans-Serif',
    color: '#fff',
  },
  inputerror: {
    borderColor: 'red',
  },
  iconStyle: {
    fontSize: 24,
    color: '#888',
    marginBottom: 10,

  },
  container3: {
    width: '80%',
    backgroundColor: '#fff',
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    height: '50%',
    marginBottom: 20,
    marginTop: '95%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3.84,
    elevation: 10,
  },
  inputContainer: {
    flexDirection: 'row',
    width: '100%',
    maxWidth: 300,
    alignItems: 'center',
  },
  inputContainers: {
    flexDirection: 'column',
    width: '100%',
    maxWidth: 275,
    marginRight: 30,
    alignItems: 'center',
    marginBottom: 30,
    justifyContent: 'space-around',
  },
  buttonLogIn:{
    backgroundColor: '#39A7FF',
    borderWidth: 0,
    margin: 5,
  },
  buttonTextLogIn: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
  },
  buttonPassword: {
    backgroundColor: '#FFEED9',
    borderWidth: 0,
    margin: 5,
  },
  buttonTextPassword: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 14,
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: '#f5f5f5',
    marginVertical: 10,
  },
  container2: {
    width: '100%',
    height: '60%',
    justifyContent: 'center',
    backgroundColor: '#39A7FF',
    position: 'absolute',
  },
  Image: {
    resizeMode: 'contain',
    width: 368,
    height: 368,
    position: 'absolute',
  },
  buttonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  ImageContainer: {
    width: '100%',
    height: 150,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  signUpContainer: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  signUpText: {
    color: '#39A7FF',
    fontWeight: 'bold',
    fontSize: 16,
  },
});

export default styles;
